### ISSUE TITLE
Explain use of asterisk (*) as valid input for BenchmarkSwitcher

### ISSUE THREAD

**Issue by mawosoft** [mawosoft/BenchmarkDotNet#4]
https://github.com/mawosoft/BenchmarkDotNet/blob/d312edcbf96ad37586119520ad6b10cbab9a95b2/src/BenchmarkDotNet/Running/UserInteraction.cs#L38-L41

**Comment by mawosoft** [comment]
See PR #2086

**Comment by YegorStepanov** [comment]
Hello, Matthias.

I'm stealing another issue from you. Do you mind, or should I check the issues in your fork first?

**Comment by mawosoft** [comment]
No, that's fine, steal away. They are mostly notes for low prio stuff or things I'm not sure about.
